"""add mini erp data layer

Revision ID: 6f481a79627c
Revises: b2c3d4e5f6a7
Create Date: 2026-06-26 16:20:28.916050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f481a79627c'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=False),
    sa.Column('approval_type', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('reviewer_role', sa.String(length=50), nullable=False),
    sa.Column('review_roles', sa.JSON(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('thread_id', sa.String(length=100), nullable=True),
    sa.Column('policy_event', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_decisions_approval_type'), ['approval_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_decisions_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_approval_decisions_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_decisions_thread_id'), ['thread_id'], unique=False)

    op.create_table('erp_change_documents',
    sa.Column('change_id', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('change_type', sa.String(length=60), nullable=False),
    sa.Column('changed_by', sa.String(length=80), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('change_id')
    )
    with op.batch_alter_table('erp_change_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_change_documents_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_change_documents_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_change_documents_object_type'), ['object_type'], unique=False)

    op.create_table('erp_currency_rates',
    sa.Column('currency_rate_id', sa.String(length=100), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('valid_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('currency_rate_id')
    )
    with op.batch_alter_table('erp_currency_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_currency_rates_from_currency'), ['from_currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_currency_rates_to_currency'), ['to_currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_currency_rates_valid_at'), ['valid_at'], unique=False)

    op.create_table('erp_process_event_logs',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('erp_process_event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_process_event_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_process_event_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_process_event_logs_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_process_event_logs_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_process_event_logs_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('erp_products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('returnable', sa.Boolean(), nullable=False),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    with op.batch_alter_table('erp_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_products_sku'), ['sku'], unique=True)

    op.create_table('erp_tenant_organizations',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('erp_warehouses',
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    with op.batch_alter_table('erp_warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_warehouses_code'), ['code'], unique=True)

    op.create_table('erp_approval_matrix_rules',
    sa.Column('approval_rule_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=False),
    sa.Column('stage_id', sa.String(length=80), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('required_role', sa.String(length=50), nullable=False),
    sa.Column('required_department_id', sa.String(length=50), nullable=True),
    sa.Column('escalation_after_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('approval_rule_id')
    )
    with op.batch_alter_table('erp_approval_matrix_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_approval_matrix_rules_scenario'), ['scenario'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_approval_matrix_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_bills_of_material',
    sa.Column('bom_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RETIRED', name='erpbomstatus'), nullable=False),
    sa.Column('output_quantity', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.PrimaryKeyConstraint('bom_id')
    )
    with op.batch_alter_table('erp_bills_of_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_bills_of_material_product_id'), ['product_id'], unique=False)

    op.create_table('erp_business_partners',
    sa.Column('partner_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('partner_type', sa.Enum('CUSTOMER', 'SUPPLIER', 'EMPLOYEE', 'BANK', 'INTERCOMPANY', name='erppartnertype'), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('tax_registration_number', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('risk_rating', sa.String(length=30), nullable=False),
    sa.Column('payment_terms', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('partner_id')
    )
    with op.batch_alter_table('erp_business_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_business_partners_partner_type'), ['partner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_business_partners_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_business_units',
    sa.Column('business_unit_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('business_unit_id')
    )
    with op.batch_alter_table('erp_business_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_business_units_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_company_codes',
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=180), nullable=False),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('fiscal_variant', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('company_code_id')
    )
    with op.batch_alter_table('erp_company_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_company_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_erp_company_codes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_consolidation_groups',
    sa.Column('group_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('reporting_currency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    with op.batch_alter_table('erp_consolidation_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_consolidation_groups_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_customer_profiles',
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('lifetime_value', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('refund_count_90d', sa.Integer(), nullable=False),
    sa.Column('complaint_count_90d', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    with op.batch_alter_table('erp_customer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_customer_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('erp_data_quality_issues',
    sa.Column('issue_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('issue_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    with op.batch_alter_table('erp_data_quality_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_data_quality_issues_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_data_quality_issues_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_data_quality_issues_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_data_quality_rules',
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('rule_type', sa.String(length=80), nullable=False),
    sa.Column('expression', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('owner_department_id', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    with op.batch_alter_table('erp_data_quality_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_data_quality_rules_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_data_quality_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_employee_profiles',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('manager_employee_id', sa.String(length=50), nullable=True),
    sa.Column('cost_center', sa.String(length=50), nullable=False),
    sa.Column('approval_limit', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    with op.batch_alter_table('erp_employee_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_employee_profiles_manager_employee_id'), ['manager_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_employee_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('erp_inventory_items',
    sa.Column('inventory_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    with op.batch_alter_table('erp_inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_inventory_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_items_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('erp_journal_entries',
    sa.Column('journal_entry_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('source_document', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='erpjournalstatus'), nullable=False),
    sa.Column('total_debit', sa.Float(), nullable=False),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('journal_entry_id')
    )
    with op.batch_alter_table('erp_journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_journal_entries_source_document'), ['source_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_journal_entries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_policy_versions',
    sa.Column('policy_version_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=3000), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RETIRED', name='erppolicystatus'), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('owner_department_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('policy_version_id')
    )
    with op.batch_alter_table('erp_policy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_policy_versions_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_policy_versions_scenario'), ['scenario'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_policy_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_bill_of_material_lines',
    sa.Column('bom_line_id', sa.String(length=120), nullable=False),
    sa.Column('bom_id', sa.String(length=100), nullable=False),
    sa.Column('component_product_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('scrap_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['erp_bills_of_material.bom_id'], ),
    sa.ForeignKeyConstraint(['component_product_id'], ['erp_products.product_id'], ),
    sa.PrimaryKeyConstraint('bom_line_id')
    )
    with op.batch_alter_table('erp_bill_of_material_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_bill_of_material_lines_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_bill_of_material_lines_component_product_id'), ['component_product_id'], unique=False)

    op.create_table('erp_departments',
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('business_unit_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('manager_employee_id', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['erp_business_units.business_unit_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    with op.batch_alter_table('erp_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_departments_business_unit_id'), ['business_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_departments_manager_employee_id'), ['manager_employee_id'], unique=False)

    op.create_table('erp_document_flows',
    sa.Column('document_flow_id', sa.String(length=120), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('source_doctype', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('target_doctype', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=False),
    sa.Column('relation_type', sa.String(length=80), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('document_flow_id')
    )
    with op.batch_alter_table('erp_document_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_document_flows_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_document_flows_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_document_flows_source_doctype'), ['source_doctype'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_document_flows_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_document_flows_target_doctype'), ['target_doctype'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_document_flows_target_id'), ['target_id'], unique=False)

    op.create_table('erp_fiscal_periods',
    sa.Column('fiscal_period_id', sa.String(length=80), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SOFT_CLOSED', 'CLOSED', name='erpfiscalperiodstatus'), nullable=False),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.PrimaryKeyConstraint('fiscal_period_id')
    )
    with op.batch_alter_table('erp_fiscal_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_fiscal_periods_company_code_id'), ['company_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_fiscal_periods_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_fiscal_periods_period'), ['period'], unique=False)

    op.create_table('erp_invoices',
    sa.Column('invoice_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'POSTED', 'CANCELLED', name='erpdocumentstatus'), nullable=False),
    sa.Column('tax_snapshot', sa.JSON(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    with op.batch_alter_table('erp_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_invoices_order_id'), ['order_id'], unique=False)

    op.create_table('erp_open_items',
    sa.Column('open_item_id', sa.String(length=120), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('business_partner_id', sa.String(length=80), nullable=True),
    sa.Column('source_document', sa.String(length=120), nullable=False),
    sa.Column('account_code', sa.String(length=80), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('clearing_document_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_partner_id'], ['erp_business_partners.partner_id'], ),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.PrimaryKeyConstraint('open_item_id')
    )
    with op.batch_alter_table('erp_open_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_open_items_business_partner_id'), ['business_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_open_items_company_code_id'), ['company_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_open_items_source_document'), ['source_document'], unique=False)

    op.create_table('erp_order_lines',
    sa.Column('line_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('fulfillment_status', sa.Enum('PENDING', 'PICKED', 'SHIPPED', 'DELIVERED', 'RETURNED', name='erpfulfillmentstatus'), nullable=False),
    sa.Column('returnable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    with op.batch_alter_table('erp_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_order_lines_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_order_lines_product_id'), ['product_id'], unique=False)

    op.create_table('erp_payment_transactions',
    sa.Column('payment_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CAPTURED', 'REFUNDED', 'FAILED', name='erppaymentstatus'), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('erp_payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_payment_transactions_order_id'), ['order_id'], unique=False)

    op.create_table('erp_refund_requests',
    sa.Column('refund_request_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'POLICY_CHECKED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'DUPLICATE_SKIPPED', name='erprefundstatus'), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=True),
    sa.Column('duplicate_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['erp_customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('refund_request_id')
    )
    with op.batch_alter_table('erp_refund_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_refund_requests_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_refund_requests_duplicate_key'), ['duplicate_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_refund_requests_order_id'), ['order_id'], unique=False)

    op.create_table('erp_sales_organizations',
    sa.Column('sales_org_id', sa.String(length=50), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('distribution_channel', sa.String(length=60), nullable=False),
    sa.Column('division', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.PrimaryKeyConstraint('sales_org_id')
    )
    with op.batch_alter_table('erp_sales_organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_sales_organizations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_erp_sales_organizations_company_code_id'), ['company_code_id'], unique=False)

    op.create_table('erp_shipments',
    sa.Column('shipment_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('carrier', sa.String(length=60), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PICKED', 'SHIPPED', 'DELIVERED', 'RETURNED', name='erpfulfillmentstatus'), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    with op.batch_alter_table('erp_shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_shipments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_shipments_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('erp_stock_reservations',
    sa.Column('reservation_id', sa.String(length=120), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('work_order_id', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'CONSUMED', 'RELEASED', 'EXPIRED', name='erpreservationstatus'), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    with op.batch_alter_table('erp_stock_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_stock_reservations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_stock_reservations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_stock_reservations_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_stock_reservations_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('erp_suppliers',
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('partner_id', sa.String(length=80), nullable=False),
    sa.Column('supplier_code', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('preferred', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['erp_business_partners.partner_id'], ),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    with op.batch_alter_table('erp_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_suppliers_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_suppliers_supplier_code'), ['supplier_code'], unique=True)

    op.create_table('erp_support_tickets',
    sa.Column('support_ticket_id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('intent', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_employee_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'WAITING_APPROVAL', 'RESOLVED', 'ESCALATED', 'CLOSED', name='erpsupportticketstatus'), nullable=False),
    sa.Column('resolution_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['erp_customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['erp_tenant_organizations.tenant_id'], ),
    sa.PrimaryKeyConstraint('support_ticket_id')
    )
    with op.batch_alter_table('erp_support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_support_tickets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_support_tickets_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_support_tickets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('erp_tax_codes',
    sa.Column('tax_code_id', sa.String(length=80), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.PrimaryKeyConstraint('tax_code_id')
    )
    with op.batch_alter_table('erp_tax_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_tax_codes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_tax_codes_company_code_id'), ['company_code_id'], unique=False)

    op.create_table('erp_business_approvals',
    sa.Column('approval_id', sa.String(length=80), nullable=False),
    sa.Column('scenario', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('refund_request_id', sa.String(length=80), nullable=True),
    sa.Column('stage_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'POSTED', 'CANCELLED', name='erpdocumentstatus'), nullable=False),
    sa.Column('required_role', sa.String(length=50), nullable=False),
    sa.Column('approver_employee_id', sa.String(length=50), nullable=True),
    sa.Column('approval_limit', sa.Float(), nullable=False),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['refund_request_id'], ['erp_refund_requests.refund_request_id'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    with op.batch_alter_table('erp_business_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_business_approvals_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_business_approvals_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_business_approvals_refund_request_id'), ['refund_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_business_approvals_scenario'), ['scenario'], unique=False)

    op.create_table('erp_consolidation_runs',
    sa.Column('consolidation_run_id', sa.String(length=120), nullable=False),
    sa.Column('group_id', sa.String(length=100), nullable=False),
    sa.Column('fiscal_period_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'POSTED', 'FAILED', name='erpconsolidationstatus'), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('total_expense', sa.Float(), nullable=False),
    sa.Column('elimination_amount', sa.Float(), nullable=False),
    sa.Column('reporting_currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['erp_fiscal_periods.fiscal_period_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['erp_consolidation_groups.group_id'], ),
    sa.PrimaryKeyConstraint('consolidation_run_id')
    )
    with op.batch_alter_table('erp_consolidation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_consolidation_runs_fiscal_period_id'), ['fiscal_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_consolidation_runs_group_id'), ['group_id'], unique=False)

    op.create_table('erp_cost_centers',
    sa.Column('cost_center_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['erp_departments.department_id'], ),
    sa.PrimaryKeyConstraint('cost_center_id')
    )
    with op.batch_alter_table('erp_cost_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_cost_centers_department_id'), ['department_id'], unique=False)

    op.create_table('erp_customer_complaints',
    sa.Column('complaint_id', sa.String(length=80), nullable=False),
    sa.Column('support_ticket_id', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('complaint_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('sentiment', sa.String(length=30), nullable=False),
    sa.Column('escalation_required', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['erp_customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['support_ticket_id'], ['erp_support_tickets.support_ticket_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    with op.batch_alter_table('erp_customer_complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_customer_complaints_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_customer_complaints_support_ticket_id'), ['support_ticket_id'], unique=False)

    op.create_table('erp_financial_ledger_entries',
    sa.Column('ledger_entry_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('refund_request_id', sa.String(length=80), nullable=True),
    sa.Column('entry_type', sa.Enum('SALE', 'PAYMENT_CAPTURE', 'REFUND', 'INVENTORY_ADJUSTMENT', name='erpledgerentrytype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('debit_account', sa.String(length=80), nullable=False),
    sa.Column('credit_account', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'POSTED', 'CANCELLED', name='erpdocumentstatus'), nullable=False),
    sa.Column('source_document', sa.String(length=120), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['refund_request_id'], ['erp_refund_requests.refund_request_id'], ),
    sa.PrimaryKeyConstraint('ledger_entry_id')
    )
    with op.batch_alter_table('erp_financial_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_financial_ledger_entries_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_financial_ledger_entries_refund_request_id'), ['refund_request_id'], unique=False)

    op.create_table('erp_inventory_batches',
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=True),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('manufacture_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_at', sa.DateTime(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['erp_suppliers.supplier_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    with op.batch_alter_table('erp_inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_inventory_batches_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_batches_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('erp_period_close_runs',
    sa.Column('close_run_id', sa.String(length=120), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('fiscal_period_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'POSTED', 'FAILED', name='erpconsolidationstatus'), nullable=False),
    sa.Column('revenue_total', sa.Float(), nullable=False),
    sa.Column('expense_total', sa.Float(), nullable=False),
    sa.Column('open_item_count', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['erp_fiscal_periods.fiscal_period_id'], ),
    sa.PrimaryKeyConstraint('close_run_id')
    )
    with op.batch_alter_table('erp_period_close_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_period_close_runs_company_code_id'), ['company_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_period_close_runs_fiscal_period_id'), ['fiscal_period_id'], unique=False)

    op.create_table('erp_plants',
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('sales_org_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.ForeignKeyConstraint(['sales_org_id'], ['erp_sales_organizations.sales_org_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('plant_id')
    )
    with op.batch_alter_table('erp_plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_plants_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_erp_plants_company_code_id'), ['company_code_id'], unique=False)

    op.create_table('erp_return_authorizations',
    sa.Column('rma_id', sa.String(length=80), nullable=False),
    sa.Column('refund_request_id', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'AUTHORIZED', 'RECEIVED', 'INSPECTED', 'RESTOCKED', 'REJECTED', name='erpreturnstatus'), nullable=False),
    sa.Column('return_label_url', sa.String(length=300), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['refund_request_id'], ['erp_refund_requests.refund_request_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('rma_id')
    )
    with op.batch_alter_table('erp_return_authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_return_authorizations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_return_authorizations_refund_request_id'), ['refund_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_return_authorizations_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('erp_fixed_assets',
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('plant_id', sa.String(length=50), nullable=True),
    sa.Column('asset_tag', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('acquisition_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('CAPITALIZED', 'IN_SERVICE', 'IMPAIRED', 'RETIRED', name='erpassetstatus'), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['erp_plants.plant_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    with op.batch_alter_table('erp_fixed_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_fixed_assets_asset_tag'), ['asset_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_erp_fixed_assets_company_code_id'), ['company_code_id'], unique=False)

    op.create_table('erp_inventory_movements',
    sa.Column('movement_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('rma_id', sa.String(length=80), nullable=True),
    sa.Column('movement_type', sa.Enum('RESERVE', 'PICK', 'SHIP', 'RETURN_RECEIPT', 'RESTOCK', 'ADJUSTMENT', name='erpinventorymovementtype'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.ForeignKeyConstraint(['rma_id'], ['erp_return_authorizations.rma_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    with op.batch_alter_table('erp_inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_inventory_movements_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_movements_rma_id'), ['rma_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('erp_inventory_serials',
    sa.Column('serial_id', sa.String(length=120), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_order_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['erp_inventory_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('serial_id')
    )
    with op.batch_alter_table('erp_inventory_serials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_inventory_serials_assigned_order_id'), ['assigned_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_serials_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_inventory_serials_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_erp_inventory_serials_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('erp_journal_lines',
    sa.Column('journal_line_id', sa.String(length=120), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=100), nullable=False),
    sa.Column('account_code', sa.String(length=80), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('cost_center_id', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['erp_cost_centers.cost_center_id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['erp_journal_entries.journal_entry_id'], ),
    sa.PrimaryKeyConstraint('journal_line_id')
    )
    with op.batch_alter_table('erp_journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_journal_lines_journal_entry_id'), ['journal_entry_id'], unique=False)

    op.create_table('erp_purchase_orders',
    sa.Column('purchase_order_id', sa.String(length=100), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ORDERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'INVOICED', 'CANCELLED', name='erpprocurementstatus'), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('expected_delivery_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['erp_plants.plant_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['erp_suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id')
    )
    with op.batch_alter_table('erp_purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_purchase_orders_company_code_id'), ['company_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_purchase_orders_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('erp_return_inspections',
    sa.Column('inspection_id', sa.String(length=80), nullable=False),
    sa.Column('rma_id', sa.String(length=80), nullable=False),
    sa.Column('inspector_employee_id', sa.String(length=50), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'DAMAGED', 'MISSING_PARTS', 'NOT_RECEIVED', name='erpinspectionresult'), nullable=False),
    sa.Column('restockable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rma_id'], ['erp_return_authorizations.rma_id'], ),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    with op.batch_alter_table('erp_return_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_return_inspections_rma_id'), ['rma_id'], unique=False)

    op.create_table('erp_work_orders',
    sa.Column('work_order_id', sa.String(length=100), nullable=False),
    sa.Column('bom_id', sa.String(length=100), nullable=False),
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'RELEASED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='erpworkorderstatus'), nullable=False),
    sa.Column('planned_quantity', sa.Integer(), nullable=False),
    sa.Column('completed_quantity', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['erp_bills_of_material.bom_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['erp_plants.plant_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.PrimaryKeyConstraint('work_order_id')
    )
    with op.batch_alter_table('erp_work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_work_orders_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_work_orders_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_work_orders_product_id'), ['product_id'], unique=False)

    op.create_table('erp_ap_invoices',
    sa.Column('ap_invoice_id', sa.String(length=100), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'MATCHED', 'APPROVED', 'POSTED', 'PAID', 'BLOCKED', name='erpapinvoicestatus'), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('source_document', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['erp_purchase_orders.purchase_order_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['erp_suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('ap_invoice_id')
    )
    with op.batch_alter_table('erp_ap_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_ap_invoices_company_code_id'), ['company_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_ap_invoices_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_ap_invoices_source_document'), ['source_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_ap_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('erp_asset_depreciation_runs',
    sa.Column('depreciation_run_id', sa.String(length=120), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('fiscal_period_id', sa.String(length=80), nullable=False),
    sa.Column('depreciation_amount', sa.Float(), nullable=False),
    sa.Column('accumulated_depreciation', sa.Float(), nullable=False),
    sa.Column('posted_journal_entry_id', sa.String(length=100), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['erp_fixed_assets.asset_id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['erp_fiscal_periods.fiscal_period_id'], ),
    sa.PrimaryKeyConstraint('depreciation_run_id')
    )
    with op.batch_alter_table('erp_asset_depreciation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_asset_depreciation_runs_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_asset_depreciation_runs_fiscal_period_id'), ['fiscal_period_id'], unique=False)

    op.create_table('erp_goods_receipts',
    sa.Column('goods_receipt_id', sa.String(length=100), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=100), nullable=False),
    sa.Column('plant_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('EXPECTED', 'RECEIVED', 'QUALITY_HOLD', 'POSTED', name='erpgoodsreceiptstatus'), nullable=False),
    sa.Column('received_by', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['erp_plants.plant_id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['erp_purchase_orders.purchase_order_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['erp_warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('goods_receipt_id')
    )
    with op.batch_alter_table('erp_goods_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_goods_receipts_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_goods_receipts_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_goods_receipts_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('erp_purchase_order_lines',
    sa.Column('po_line_id', sa.String(length=120), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_code_id', sa.String(length=80), nullable=True),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['erp_purchase_orders.purchase_order_id'], ),
    sa.ForeignKeyConstraint(['tax_code_id'], ['erp_tax_codes.tax_code_id'], ),
    sa.PrimaryKeyConstraint('po_line_id')
    )
    with op.batch_alter_table('erp_purchase_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_purchase_order_lines_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_purchase_order_lines_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('erp_work_order_component_issues',
    sa.Column('issue_id', sa.String(length=120), nullable=False),
    sa.Column('work_order_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['erp_inventory_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['erp_work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    with op.batch_alter_table('erp_work_order_component_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_work_order_component_issues_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_work_order_component_issues_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('erp_goods_receipt_lines',
    sa.Column('gr_line_id', sa.String(length=120), nullable=False),
    sa.Column('goods_receipt_id', sa.String(length=100), nullable=False),
    sa.Column('po_line_id', sa.String(length=120), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['erp_goods_receipts.goods_receipt_id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['erp_purchase_order_lines.po_line_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.product_id'], ),
    sa.PrimaryKeyConstraint('gr_line_id')
    )
    with op.batch_alter_table('erp_goods_receipt_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_goods_receipt_lines_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_goods_receipt_lines_goods_receipt_id'), ['goods_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_goods_receipt_lines_po_line_id'), ['po_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_goods_receipt_lines_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_goods_receipt_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_goods_receipt_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_goods_receipt_lines_po_line_id'))
        batch_op.drop_index(batch_op.f('ix_erp_goods_receipt_lines_goods_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_erp_goods_receipt_lines_batch_id'))

    op.drop_table('erp_goods_receipt_lines')
    with op.batch_alter_table('erp_work_order_component_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_work_order_component_issues_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_work_order_component_issues_product_id'))

    op.drop_table('erp_work_order_component_issues')
    with op.batch_alter_table('erp_purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_purchase_order_lines_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_purchase_order_lines_product_id'))

    op.drop_table('erp_purchase_order_lines')
    with op.batch_alter_table('erp_goods_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_goods_receipts_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_goods_receipts_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_goods_receipts_plant_id'))

    op.drop_table('erp_goods_receipts')
    with op.batch_alter_table('erp_asset_depreciation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_asset_depreciation_runs_fiscal_period_id'))
        batch_op.drop_index(batch_op.f('ix_erp_asset_depreciation_runs_asset_id'))

    op.drop_table('erp_asset_depreciation_runs')
    with op.batch_alter_table('erp_ap_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_ap_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_erp_ap_invoices_source_document'))
        batch_op.drop_index(batch_op.f('ix_erp_ap_invoices_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_ap_invoices_company_code_id'))

    op.drop_table('erp_ap_invoices')
    with op.batch_alter_table('erp_work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_work_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_work_orders_plant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_work_orders_bom_id'))

    op.drop_table('erp_work_orders')
    with op.batch_alter_table('erp_return_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_return_inspections_rma_id'))

    op.drop_table('erp_return_inspections')
    with op.batch_alter_table('erp_purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_erp_purchase_orders_plant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_purchase_orders_company_code_id'))

    op.drop_table('erp_purchase_orders')
    with op.batch_alter_table('erp_journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_journal_lines_journal_entry_id'))

    op.drop_table('erp_journal_lines')
    with op.batch_alter_table('erp_inventory_serials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_inventory_serials_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_serials_serial_number'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_serials_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_serials_assigned_order_id'))

    op.drop_table('erp_inventory_serials')
    with op.batch_alter_table('erp_inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_inventory_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_movements_rma_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_movements_order_id'))

    op.drop_table('erp_inventory_movements')
    with op.batch_alter_table('erp_fixed_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_fixed_assets_company_code_id'))
        batch_op.drop_index(batch_op.f('ix_erp_fixed_assets_asset_tag'))

    op.drop_table('erp_fixed_assets')
    with op.batch_alter_table('erp_return_authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_return_authorizations_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_return_authorizations_refund_request_id'))
        batch_op.drop_index(batch_op.f('ix_erp_return_authorizations_order_id'))

    op.drop_table('erp_return_authorizations')
    with op.batch_alter_table('erp_plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_plants_company_code_id'))
        batch_op.drop_index(batch_op.f('ix_erp_plants_code'))

    op.drop_table('erp_plants')
    with op.batch_alter_table('erp_period_close_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_period_close_runs_fiscal_period_id'))
        batch_op.drop_index(batch_op.f('ix_erp_period_close_runs_company_code_id'))

    op.drop_table('erp_period_close_runs')
    with op.batch_alter_table('erp_inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_inventory_batches_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_batches_batch_number'))

    op.drop_table('erp_inventory_batches')
    with op.batch_alter_table('erp_financial_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_financial_ledger_entries_refund_request_id'))
        batch_op.drop_index(batch_op.f('ix_erp_financial_ledger_entries_order_id'))

    op.drop_table('erp_financial_ledger_entries')
    with op.batch_alter_table('erp_customer_complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_customer_complaints_support_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_erp_customer_complaints_customer_id'))

    op.drop_table('erp_customer_complaints')
    with op.batch_alter_table('erp_cost_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_cost_centers_department_id'))

    op.drop_table('erp_cost_centers')
    with op.batch_alter_table('erp_consolidation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_consolidation_runs_group_id'))
        batch_op.drop_index(batch_op.f('ix_erp_consolidation_runs_fiscal_period_id'))

    op.drop_table('erp_consolidation_runs')
    with op.batch_alter_table('erp_business_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_business_approvals_scenario'))
        batch_op.drop_index(batch_op.f('ix_erp_business_approvals_refund_request_id'))
        batch_op.drop_index(batch_op.f('ix_erp_business_approvals_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_business_approvals_object_id'))

    op.drop_table('erp_business_approvals')
    with op.batch_alter_table('erp_tax_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_tax_codes_company_code_id'))
        batch_op.drop_index(batch_op.f('ix_erp_tax_codes_code'))

    op.drop_table('erp_tax_codes')
    with op.batch_alter_table('erp_support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_support_tickets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_support_tickets_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_support_tickets_customer_id'))

    op.drop_table('erp_support_tickets')
    with op.batch_alter_table('erp_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_suppliers_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_erp_suppliers_partner_id'))

    op.drop_table('erp_suppliers')
    with op.batch_alter_table('erp_stock_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_stock_reservations_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_stock_reservations_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_stock_reservations_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_stock_reservations_order_id'))

    op.drop_table('erp_stock_reservations')
    with op.batch_alter_table('erp_shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_shipments_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_shipments_order_id'))

    op.drop_table('erp_shipments')
    with op.batch_alter_table('erp_sales_organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_sales_organizations_company_code_id'))
        batch_op.drop_index(batch_op.f('ix_erp_sales_organizations_code'))

    op.drop_table('erp_sales_organizations')
    with op.batch_alter_table('erp_refund_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_refund_requests_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_refund_requests_duplicate_key'))
        batch_op.drop_index(batch_op.f('ix_erp_refund_requests_customer_id'))

    op.drop_table('erp_refund_requests')
    with op.batch_alter_table('erp_payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_payment_transactions_order_id'))

    op.drop_table('erp_payment_transactions')
    with op.batch_alter_table('erp_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_order_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_order_lines_order_id'))

    op.drop_table('erp_order_lines')
    with op.batch_alter_table('erp_open_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_open_items_source_document'))
        batch_op.drop_index(batch_op.f('ix_erp_open_items_company_code_id'))
        batch_op.drop_index(batch_op.f('ix_erp_open_items_business_partner_id'))

    op.drop_table('erp_open_items')
    with op.batch_alter_table('erp_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_invoices_order_id'))

    op.drop_table('erp_invoices')
    with op.batch_alter_table('erp_fiscal_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_fiscal_periods_period'))
        batch_op.drop_index(batch_op.f('ix_erp_fiscal_periods_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_erp_fiscal_periods_company_code_id'))

    op.drop_table('erp_fiscal_periods')
    with op.batch_alter_table('erp_document_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_document_flows_target_id'))
        batch_op.drop_index(batch_op.f('ix_erp_document_flows_target_doctype'))
        batch_op.drop_index(batch_op.f('ix_erp_document_flows_source_id'))
        batch_op.drop_index(batch_op.f('ix_erp_document_flows_source_doctype'))
        batch_op.drop_index(batch_op.f('ix_erp_document_flows_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_document_flows_case_id'))

    op.drop_table('erp_document_flows')
    with op.batch_alter_table('erp_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_departments_manager_employee_id'))
        batch_op.drop_index(batch_op.f('ix_erp_departments_business_unit_id'))

    op.drop_table('erp_departments')
    with op.batch_alter_table('erp_bill_of_material_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_bill_of_material_lines_component_product_id'))
        batch_op.drop_index(batch_op.f('ix_erp_bill_of_material_lines_bom_id'))

    op.drop_table('erp_bill_of_material_lines')
    with op.batch_alter_table('erp_policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_policy_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_policy_versions_scenario'))
        batch_op.drop_index(batch_op.f('ix_erp_policy_versions_policy_id'))

    op.drop_table('erp_policy_versions')
    with op.batch_alter_table('erp_journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_journal_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_journal_entries_source_document'))

    op.drop_table('erp_journal_entries')
    with op.batch_alter_table('erp_inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_inventory_items_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_erp_inventory_items_product_id'))

    op.drop_table('erp_inventory_items')
    with op.batch_alter_table('erp_employee_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_employee_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_erp_employee_profiles_manager_employee_id'))

    op.drop_table('erp_employee_profiles')
    with op.batch_alter_table('erp_data_quality_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_data_quality_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_data_quality_rules_object_type'))

    op.drop_table('erp_data_quality_rules')
    with op.batch_alter_table('erp_data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_data_quality_issues_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_data_quality_issues_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_data_quality_issues_object_id'))

    op.drop_table('erp_data_quality_issues')
    with op.batch_alter_table('erp_customer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_customer_profiles_user_id'))

    op.drop_table('erp_customer_profiles')
    with op.batch_alter_table('erp_consolidation_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_consolidation_groups_tenant_id'))

    op.drop_table('erp_consolidation_groups')
    with op.batch_alter_table('erp_company_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_company_codes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_company_codes_code'))

    op.drop_table('erp_company_codes')
    with op.batch_alter_table('erp_business_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_business_units_tenant_id'))

    op.drop_table('erp_business_units')
    with op.batch_alter_table('erp_business_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_business_partners_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_business_partners_partner_type'))

    op.drop_table('erp_business_partners')
    with op.batch_alter_table('erp_bills_of_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_bills_of_material_product_id'))

    op.drop_table('erp_bills_of_material')
    with op.batch_alter_table('erp_approval_matrix_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_approval_matrix_rules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_erp_approval_matrix_rules_scenario'))

    op.drop_table('erp_approval_matrix_rules')
    with op.batch_alter_table('erp_warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_warehouses_code'))

    op.drop_table('erp_warehouses')
    op.drop_table('erp_tenant_organizations')
    with op.batch_alter_table('erp_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_products_sku'))

    op.drop_table('erp_products')
    with op.batch_alter_table('erp_process_event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_process_event_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_erp_process_event_logs_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_process_event_logs_object_id'))
        batch_op.drop_index(batch_op.f('ix_erp_process_event_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_erp_process_event_logs_case_id'))

    op.drop_table('erp_process_event_logs')
    with op.batch_alter_table('erp_currency_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_currency_rates_valid_at'))
        batch_op.drop_index(batch_op.f('ix_erp_currency_rates_to_currency'))
        batch_op.drop_index(batch_op.f('ix_erp_currency_rates_from_currency'))

    op.drop_table('erp_currency_rates')
    with op.batch_alter_table('erp_change_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_change_documents_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_change_documents_object_id'))
        batch_op.drop_index(batch_op.f('ix_erp_change_documents_changed_at'))

    op.drop_table('erp_change_documents')
    with op.batch_alter_table('approval_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_decisions_thread_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decisions_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decisions_request_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decisions_approval_type'))

    op.drop_table('approval_decisions')
    # ### end Alembic commands ###
