"""add operator_id to ticket table

Revision ID: 8b66a065f61b
Revises: 31e398c9ae24
Create Date: 2026-03-22 16:02:19.277412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b66a065f61b'
down_revision: Union[str, Sequence[str], None] = '31e398c9ae24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_operator_id_users', 'users', ['operator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_operator_id_users', type_='foreignkey')
        batch_op.drop_column('operator_id')

    # ### end Alembic commands ###
