"""add enterprise erp governance layer

Revision ID: a902ebde4f49
Revises: 6f481a79627c
Create Date: 2026-06-26 22:36:07.305380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a902ebde4f49'
down_revision: Union[str, Sequence[str], None] = '6f481a79627c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_access_requests',
    sa.Column('access_request_id', sa.String(length=120), nullable=False),
    sa.Column('requester_employee_id', sa.String(length=50), nullable=False),
    sa.Column('target_system', sa.String(length=120), nullable=False),
    sa.Column('permission_level', sa.String(length=80), nullable=False),
    sa.Column('business_reason', sa.String(length=500), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'CANCELLED', 'TIMEOUT', name='erpbusinessrequeststatus'), nullable=False),
    sa.Column('approval_due_at', sa.DateTime(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('policy_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('access_request_id')
    )
    with op.batch_alter_table('erp_access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_access_requests_requester_employee_id'), ['requester_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_access_requests_target_system'), ['target_system'], unique=False)

    op.create_table('erp_compensation_transactions',
    sa.Column('compensation_id', sa.String(length=120), nullable=False),
    sa.Column('saga_id', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'FAILED', 'SKIPPED', name='erpcompensationstatus'), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('compensation_id')
    )
    with op.batch_alter_table('erp_compensation_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_compensation_transactions_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_compensation_transactions_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_compensation_transactions_saga_id'), ['saga_id'], unique=False)

    op.create_table('erp_external_system_connectors',
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('system_type', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('auth_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', 'DRAFT', name='erpconnectorstatus'), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('connector_id')
    )
    with op.batch_alter_table('erp_external_system_connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_external_system_connectors_system_type'), ['system_type'], unique=False)

    op.create_table('erp_idempotency_records',
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='erpidempotencystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    with op.batch_alter_table('erp_idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_idempotency_records_scope'), ['scope'], unique=False)

    op.create_table('erp_master_data_change_requests',
    sa.Column('mdg_request_id', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('change_type', sa.String(length=80), nullable=False),
    sa.Column('proposed_change', sa.JSON(), nullable=False),
    sa.Column('validation_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATING', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'APPLIED', name='erpmasterdatarequeststatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=80), nullable=False),
    sa.Column('reviewer_employee_id', sa.String(length=50), nullable=True),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mdg_request_id')
    )
    with op.batch_alter_table('erp_master_data_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_master_data_change_requests_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_master_data_change_requests_object_type'), ['object_type'], unique=False)

    op.create_table('erp_master_data_duplicate_candidates',
    sa.Column('duplicate_id', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('left_object_id', sa.String(length=120), nullable=False),
    sa.Column('right_object_id', sa.String(length=120), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matched_fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('duplicate_id')
    )
    with op.batch_alter_table('erp_master_data_duplicate_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_master_data_duplicate_candidates_left_object_id'), ['left_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_master_data_duplicate_candidates_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_master_data_duplicate_candidates_right_object_id'), ['right_object_id'], unique=False)

    op.create_table('erp_master_data_versions',
    sa.Column('version_id', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.String(length=80), nullable=False),
    sa.Column('change_reason', sa.String(length=300), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    with op.batch_alter_table('erp_master_data_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_master_data_versions_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_master_data_versions_object_type'), ['object_type'], unique=False)

    op.create_table('erp_outbox_events',
    sa.Column('outbox_event_id', sa.String(length=120), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'FAILED', 'DEAD_LETTER', name='erpoutboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('outbox_event_id')
    )
    with op.batch_alter_table('erp_outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_outbox_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_outbox_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_outbox_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_outbox_events_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('erp_reversal_documents',
    sa.Column('reversal_document_id', sa.String(length=120), nullable=False),
    sa.Column('source_document', sa.String(length=120), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'POSTED', 'CANCELLED', name='erpdocumentstatus'), nullable=False),
    sa.Column('posted_journal_entry_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reversal_document_id')
    )
    with op.batch_alter_table('erp_reversal_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_reversal_documents_source_document'), ['source_document'], unique=False)

    op.create_table('erp_system_reconciliation_issues',
    sa.Column('reconciliation_issue_id', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('target_system', sa.String(length=80), nullable=False),
    sa.Column('mismatch_type', sa.String(length=100), nullable=False),
    sa.Column('source_snapshot', sa.JSON(), nullable=True),
    sa.Column('target_snapshot', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reconciliation_issue_id')
    )
    with op.batch_alter_table('erp_system_reconciliation_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_system_reconciliation_issues_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_system_reconciliation_issues_object_type'), ['object_type'], unique=False)

    op.create_table('erp_webhook_subscriptions',
    sa.Column('subscription_id', sa.String(length=120), nullable=False),
    sa.Column('connector_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('target_url', sa.String(length=300), nullable=False),
    sa.Column('secret_ref', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['erp_external_system_connectors.connector_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    with op.batch_alter_table('erp_webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_webhook_subscriptions_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_webhook_subscriptions_event_type'), ['event_type'], unique=False)

    op.create_table('erp_clearing_documents',
    sa.Column('clearing_document_id', sa.String(length=120), nullable=False),
    sa.Column('company_code_id', sa.String(length=50), nullable=False),
    sa.Column('business_partner_id', sa.String(length=80), nullable=True),
    sa.Column('clearing_type', sa.String(length=60), nullable=False),
    sa.Column('source_document', sa.String(length=120), nullable=False),
    sa.Column('target_document', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'POSTED', 'CANCELLED', name='erpdocumentstatus'), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_partner_id'], ['erp_business_partners.partner_id'], ),
    sa.ForeignKeyConstraint(['company_code_id'], ['erp_company_codes.company_code_id'], ),
    sa.PrimaryKeyConstraint('clearing_document_id')
    )
    with op.batch_alter_table('erp_clearing_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_clearing_documents_company_code_id'), ['company_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_clearing_documents_source_document'), ['source_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_clearing_documents_target_document'), ['target_document'], unique=False)

    op.create_table('erp_master_data_validation_results',
    sa.Column('validation_result_id', sa.String(length=120), nullable=False),
    sa.Column('mdg_request_id', sa.String(length=120), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mdg_request_id'], ['erp_master_data_change_requests.mdg_request_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['erp_data_quality_rules.rule_id'], ),
    sa.PrimaryKeyConstraint('validation_result_id')
    )
    with op.batch_alter_table('erp_master_data_validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_master_data_validation_results_mdg_request_id'), ['mdg_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_master_data_validation_results_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_master_data_validation_results_object_type'), ['object_type'], unique=False)

    op.create_table('erp_credit_memos',
    sa.Column('credit_memo_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('refund_request_id', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('source_invoice_id', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'POSTED', 'CANCELLED', name='erpdocumentstatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['erp_customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['refund_request_id'], ['erp_refund_requests.refund_request_id'], ),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['erp_invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('credit_memo_id')
    )
    with op.batch_alter_table('erp_credit_memos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_credit_memos_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_credit_memos_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_credit_memos_refund_request_id'), ['refund_request_id'], unique=False)

    op.create_table('erp_reimbursement_claims',
    sa.Column('reimbursement_id', sa.String(length=120), nullable=False),
    sa.Column('requester_employee_id', sa.String(length=50), nullable=False),
    sa.Column('cost_center_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('receipt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'CANCELLED', 'TIMEOUT', name='erpbusinessrequeststatus'), nullable=False),
    sa.Column('approval_due_at', sa.DateTime(), nullable=True),
    sa.Column('policy_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['erp_cost_centers.cost_center_id'], ),
    sa.PrimaryKeyConstraint('reimbursement_id')
    )
    with op.batch_alter_table('erp_reimbursement_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_reimbursement_claims_cost_center_id'), ['cost_center_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_reimbursement_claims_requester_employee_id'), ['requester_employee_id'], unique=False)

    op.create_table('erp_procurement_approval_requests',
    sa.Column('procurement_request_id', sa.String(length=120), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=100), nullable=False),
    sa.Column('requester_employee_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'CANCELLED', 'TIMEOUT', name='erpbusinessrequeststatus'), nullable=False),
    sa.Column('approval_due_at', sa.DateTime(), nullable=True),
    sa.Column('policy_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['erp_purchase_orders.purchase_order_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['erp_suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('procurement_request_id')
    )
    with op.batch_alter_table('erp_procurement_approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_procurement_approval_requests_purchase_order_id'), ['purchase_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_procurement_approval_requests_requester_employee_id'), ['requester_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_procurement_approval_requests_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_procurement_approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_procurement_approval_requests_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_erp_procurement_approval_requests_requester_employee_id'))
        batch_op.drop_index(batch_op.f('ix_erp_procurement_approval_requests_purchase_order_id'))

    op.drop_table('erp_procurement_approval_requests')
    with op.batch_alter_table('erp_reimbursement_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_reimbursement_claims_requester_employee_id'))
        batch_op.drop_index(batch_op.f('ix_erp_reimbursement_claims_cost_center_id'))

    op.drop_table('erp_reimbursement_claims')
    with op.batch_alter_table('erp_credit_memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_credit_memos_refund_request_id'))
        batch_op.drop_index(batch_op.f('ix_erp_credit_memos_order_id'))
        batch_op.drop_index(batch_op.f('ix_erp_credit_memos_customer_id'))

    op.drop_table('erp_credit_memos')
    with op.batch_alter_table('erp_master_data_validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_master_data_validation_results_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_master_data_validation_results_object_id'))
        batch_op.drop_index(batch_op.f('ix_erp_master_data_validation_results_mdg_request_id'))

    op.drop_table('erp_master_data_validation_results')
    with op.batch_alter_table('erp_clearing_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_clearing_documents_target_document'))
        batch_op.drop_index(batch_op.f('ix_erp_clearing_documents_source_document'))
        batch_op.drop_index(batch_op.f('ix_erp_clearing_documents_company_code_id'))

    op.drop_table('erp_clearing_documents')
    with op.batch_alter_table('erp_webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_webhook_subscriptions_event_type'))
        batch_op.drop_index(batch_op.f('ix_erp_webhook_subscriptions_connector_id'))

    op.drop_table('erp_webhook_subscriptions')
    with op.batch_alter_table('erp_system_reconciliation_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_system_reconciliation_issues_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_system_reconciliation_issues_object_id'))

    op.drop_table('erp_system_reconciliation_issues')
    with op.batch_alter_table('erp_reversal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_reversal_documents_source_document'))

    op.drop_table('erp_reversal_documents')
    with op.batch_alter_table('erp_outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_outbox_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_erp_outbox_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_erp_outbox_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_erp_outbox_events_aggregate_id'))

    op.drop_table('erp_outbox_events')
    with op.batch_alter_table('erp_master_data_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_master_data_versions_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_master_data_versions_object_id'))

    op.drop_table('erp_master_data_versions')
    with op.batch_alter_table('erp_master_data_duplicate_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_master_data_duplicate_candidates_right_object_id'))
        batch_op.drop_index(batch_op.f('ix_erp_master_data_duplicate_candidates_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_master_data_duplicate_candidates_left_object_id'))

    op.drop_table('erp_master_data_duplicate_candidates')
    with op.batch_alter_table('erp_master_data_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_master_data_change_requests_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_master_data_change_requests_object_id'))

    op.drop_table('erp_master_data_change_requests')
    with op.batch_alter_table('erp_idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_idempotency_records_scope'))

    op.drop_table('erp_idempotency_records')
    with op.batch_alter_table('erp_external_system_connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_external_system_connectors_system_type'))

    op.drop_table('erp_external_system_connectors')
    with op.batch_alter_table('erp_compensation_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_compensation_transactions_saga_id'))
        batch_op.drop_index(batch_op.f('ix_erp_compensation_transactions_object_type'))
        batch_op.drop_index(batch_op.f('ix_erp_compensation_transactions_object_id'))

    op.drop_table('erp_compensation_transactions')
    with op.batch_alter_table('erp_access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_access_requests_target_system'))
        batch_op.drop_index(batch_op.f('ix_erp_access_requests_requester_employee_id'))

    op.drop_table('erp_access_requests')
    # ### end Alembic commands ###
